#!/usr/bin/env python3
"""Temporary Phase-0 audit for prompt-stash. Produces AUDIT.md at repo root."""
import re
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / "prompts"
VAR_RE = re.compile(r"\{([A-Za-z0-9_ -]+)\}")
GOOD_VAR_RE = re.compile(r"^[a-z][a-z0-9_]*$")
ARABIC_RE = re.compile(r"[\u0600-\u06FF]")
LANGVAR_RE = re.compile(r"\{(language|languages|reply_language|language_and_tone|audience_language|dialect)\}")

files = sorted(PROMPTS.glob("*/*.txt"))
rows, missing_example, bad_style, arabic_no_header, langvar_files, short_bodies, no_rules, no_task, titles = [], [], [], [], [], [], [], [], []
all_vars = Counter()

for f in files:
    rel = f.relative_to(ROOT).as_posix()
    folder = f.parent.name
    text = f.read_text(encoding="utf-8")
    lines = text.splitlines()
    title = lines[0].strip() if lines else "(empty)"
    titles.append((title, rel))
    words = len(text.split())
    has_example = any(l.startswith("# Example values:") for l in lines)
    has_rules = any(l.strip().upper().endswith("RULES") for l in lines)
    has_task = "TASK" in text
    body_vars = set()
    for l in lines:
        if l.startswith("# Example values:"):
            continue
        for m in VAR_RE.findall(l):
            body_vars.add(m.strip())
            all_vars[m.strip()] += 1
            if not GOOD_VAR_RE.match(m.strip()):
                bad_style.append((rel, m.strip()))
    if not has_example:
        missing_example.append(rel)
    if ARABIC_RE.search(text):
        arabic_no_header.append(rel)
    if LANGVAR_RE.search(text):
        langvar_files.append(rel)
    if words < 80:
        short_bodies.append((rel, words))
    if not has_rules:
        no_rules.append(rel)
    if not has_task:
        no_task.append(rel)
    rows.append((folder, rel, title, words, len(body_vars)))

counts = Counter(r[0] for r in rows)
dup_titles = [t for t, c in Counter(t[0] for t in titles).items() if c > 1]

L = []
L.append("# AUDIT — Phase 0 (temporary file, deleted before merge)\n")
L.append(f"Generated by scripts/audit_temp.py against the working tree.\n")
L.append("## Counts\n")
L.append(f"- Total prompt files: **{len(rows)}**")
for folder in sorted(counts):
    L.append(f"- {folder}: {counts[folder]}")
L.append("")
L.append("## Format deviations (vs. current v3 convention)\n")
L.append(f"- Files missing the `# Example values:` line: **{len(missing_example)}**")
for r in missing_example:
    L.append(f"  - `{r}`")
L.append(f"- Files with **no `Language:` header** (format gap — Phase 1 adds it): **{len(rows)}** (all)")
L.append(f"- Files with **no `Tags:` header**: **{len(rows)}** (all)")
L.append(f"- Files with **no `# Variables` block**: **{len(rows)}** (all — variables used but never declared)")
L.append(f"- Files missing a `RULES` section: **{len(no_rules)}**")
for r in no_rules:
    L.append(f"  - `{r}`")
L.append(f"- Files without any task/structure marker ('TASK'): **{len(no_task)}**")
for r in no_task:
    L.append(f"  - `{r}`")
L.append("")
L.append("## Variable style check\n")
if bad_style:
    L.append(f"- **{len(bad_style)} violations** of {{snake_case}}:")
    for rel, v in bad_style:
        L.append(f"  - `{rel}`: {{{v}}}")
else:
    L.append("- No violations: every variable across all files is already snake_case.")
uniq = sorted(all_vars.items(), key=lambda x: -x[1])
L.append(f"- Distinct variable names: **{len(all_vars)}**; top 15: " + ", ".join(f"`{{{v}}}`×{c}" for v, c in uniq[:15]))
L.append("")
L.append("## Language mixing (Arabic present, no header declares it)\n")
L.append(f"- Files containing Arabic text: **{len(arabic_no_header)}** — none declare output language today.")
for r in arabic_no_header:
    L.append(f"  - `{r}`")
L.append(f"- Files with an explicit language *variable* (should map to `output=user-choice`): **{len(langvar_files)}**")
for r in langvar_files:
    L.append(f"  - `{r}`")
L.append("")
L.append("## Sensitive-topic prompts (need Phase-2 safety notes)\n")
L.append("- **Legal/contracts**: contract-summary, rental-contract-explain, legal-terms-explain, complaint-letter-eg")
L.append("- **Financial**: budget-split, salary-negotiation-email, price-calc-explain, discount-offer, idea-check, quotation-writer, late-payment-chaser, referral-offer, seasonal-campaign, invoice-words")
L.append("- **Health**: workout-plan, sleep-routine")
L.append("- **Security (all defensive)**: all 10 files in security-basics/")
L.append("- **User pastes personal/client data**: meeting-notes-fix, store-reply, reply-tone, comment-reply, csv-cleaner, data-summarizer, pdf-extract, duplicate-finder, log-analyzer, code-reviewer, bug-repro-steps, customer-persona")
L.append("")
L.append("## Duplicated purpose (near-dupes reviewed; all judged distinct)\n")
L.append("- sql-fix (repairs a broken query) vs sql-from-question (writes a new query) — distinct, stated in when-to-use.")
L.append("- meeting-agenda (before) vs meeting-notes-fix (after) — distinct.")
L.append("- cv-bullets (phrasing bullets) vs cv-reviewer (whole-CV review) vs freelance-profile (platform profile) — distinct.")
L.append("- contract-summary (any contract) vs rental-contract-explain (Arabic rentals) — distinct domain/language.")
L.append("- price-calc-explain (justify price) vs discount-offer (design a promo) — distinct.")
L.append("")
L.append("## Vague / short files\n")
if short_bodies:
    for rel, w in short_bodies:
        L.append(f"- `{rel}` — only {w} words")
else:
    L.append("- None below 80 words; all prompts carry role, task order, and constraints.")
L.append("")
L.append(f"- Duplicate titles: {', '.join(dup_titles) if dup_titles else 'none'}")
L.append("- Filler phrases ('world's best', 'I cannot stress enough'): none found.")
L.append("- Typos spotted on read-through: 'contrat مسجل' inside legal-terms-explain example values (should be 'عقد مسجل'); 'الخطرعة' should be 'الخطيرة' in rental-contract-explain; 'the courier'/'the real' fine elsewhere. Fixed in Phase 1.")
L.append("")
L.append("## Per-file inventory\n")
L.append("| Folder | File | Title | Words | Vars |")
L.append("|---|---|---|---|---|")
for folder, rel, title, words, nvars in rows:
    L.append(f"| {folder} | `{rel}` | {title} | {words} | {nvars} |")
L.append("")

(ROOT / "AUDIT.md").write_text("\n".join(L), encoding="utf-8")
print(f"folders={len(counts)} files={len(rows)} missing_example={len(missing_example)} bad_style={len(bad_style)} arabic_no_header={len(arabic_no_header)} langvar={len(langvar_files)} no_rules={len(no_rules)} no_task={len(no_task)} distinct_vars={len(all_vars)}")
