#!/usr/bin/env python3
"""Build prompts.json, the per-folder READMEs, and docs/search.html from the prompt files.

Standard library only. Idempotent: run after any prompt change so the docs
and the machine-readable index never drift from the actual files.

All generated content is produced by generate() as {relative_path: text};
main() only writes it to disk. validate_prompts.py imports generate() so its
staleness check can compare on-disk files against freshly generated output
without duplicating the logic.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / "prompts"
LANG_RE = re.compile(r"^Language: prompt=(EN|AR) \| output=(EN|AR|EN\+AR|user-choice)$")

FOLDER_META = {
    "debugging": ("🐞", "Fix the thing that broke — websites, Windows, printers, batteries, email."),
    "work": ("💼", "Meetings, emails, priorities and the career conversations in between."),
    "content": ("✍️", "Posts, captions, hooks and calendars — bilingual where it matters."),
    "study": ("📚", "Understand faster and remember longer — notes, quizzes, plans."),
    "business": ("🏪", "Run a small business: clients, quotes, invoices, complaints."),
    "dev": ("💻", "Everyday developer repairs — git, SQL, logs, reviews, Docker."),
    "daily": ("🌱", "Money, food, sleep, habits and the choices in between."),
    "ai-coding": ("🤖", "Work with AI coding tools: better prompts, tests, refactors, reviews."),
    "career": ("🎯", "Job search and promotion — CVs, interviews, LinkedIn, negotiations."),
    "marketing": ("📣", "Ads, WhatsApp, landing pages and seasons for small businesses."),
    "files-data": ("🗃️", "Tame spreadsheets, PDFs and folders into clean answers."),
    "security-basics": ("🔐", "Defensive everyday security — no fear, just checklists."),
    "arabic-life": ("🇪🇬", "Formal Arabic, Egyptian dialect and Egypt paperwork — done right."),
}

# Files that must carry a human-readable disclaimer (line 5) and a "Note:" line
# in the body. Single source of truth: validate_prompts.py imports this set.
SAFETY_REQUIRED = {
    "business/contract-summary", "arabic-life/rental-contract-explain",
    "arabic-life/legal-terms-explain", "arabic-life/complaint-letter-eg",
    "work/salary-negotiation-email", "business/invoice-words",
    "business/price-calc-explain", "business/quotation-writer",
    "business/late-payment-chaser", "business/idea-check",
    "daily/budget-split", "marketing/discount-offer", "marketing/referral-offer",
    "marketing/seasonal-campaign", "daily/expenses-review", "daily/decision-matrix",
    "daily/workout-plan", "daily/sleep-routine",
    "security-basics/password-checkup", "security-basics/phishing-spotter",
    "security-basics/2fa-setup-guide", "security-basics/scam-check",
    "security-basics/breach-response", "security-basics/public-wifi-safety",
    "security-basics/device-loss-plan", "security-basics/backup-plan",
    "security-basics/privacy-audit", "security-basics/safe-downloads",
    "arabic-life/paperwork-guide", "dev/security-review",
}


def parse(f: Path) -> dict:
    lines = f.read_text(encoding="utf-8").splitlines()
    lang = LANG_RE.match(lines[2])
    tags = [t.strip() for t in lines[3][len("Tags: "):].split(",") if t.strip()]
    idx = next(i for i, l in enumerate(lines) if l.strip() == "# Variables")
    variables = [re.match(r"^- \{([a-z0-9_]+)\}:", l).group(1)
                 for l in lines[idx + 1:] if l.startswith("- {")]
    stem = f.relative_to(PROMPTS).as_posix()[:-4]
    return {
        "title": lines[0].strip(),
        "when_to_use": lines[1][len("When to use it:"):].strip(),
        "folder": f.parent.name,
        "path": f.relative_to(ROOT).as_posix(),
        "language": {"prompt": lang.group(1), "output": lang.group(2)},
        "tags": tags,
        "variables": variables,
        "safety": stem in SAFETY_REQUIRED,
    }


def load_records() -> list[dict]:
    records = [parse(f) for f in sorted(PROMPTS.glob("*/*.txt"))]
    records.sort(key=lambda r: (r["folder"], r["path"]))
    return records


def render_index(records: list[dict]) -> str:
    folders = {name: sum(1 for r in records if r["folder"] == name) for name in FOLDER_META}
    index = {
        "name": "Prompt Stash",
        "total": len(records),
        "folders": folders,
        "prompts": records,
    }
    return json.dumps(index, ensure_ascii=False, indent=2) + "\n"


def render_folder_readme(folder: str, records: list[dict]) -> str:
    emoji, blurb = FOLDER_META[folder]
    items = [r for r in records if r["folder"] == folder]
    out = [f"# {emoji} {folder} — {len(items)} prompts", "",
           f"> {blurb}", "",
           "<!-- GENERATED by scripts/build_index.py — edit the .txt files, not this table. -->", "",
           f"← Back to the [main README](../../README.md).", "",
           "| File | Title | When to use it | Language | Tags |",
           "|---|---|---|---|---|"]
    for r in items:
        name = Path(r["path"]).name
        lang = f"{r['language']['prompt']}→{r['language']['output']}"
        tags = ", ".join(r["tags"])
        out.append(f"| [`{name}`]({name}) | {r['title']} | {r['when_to_use']} | {lang} | {tags} |")
    out += ["", "## File format", "",
            "Title · when-to-use · `Language:` · `Tags:` · body · `# Variables` · `# Example values`.",
            "See [CONTRIBUTING.md](../../CONTRIBUTING.md#the-format-non-negotiable) for the full spec.", ""]
    return "\n".join(out)


SEARCH_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Prompt Stash — search {total} prompts</title>
<style>
  :root {{ color-scheme: light dark; --bg:#0f172a; --card:#1e293b; --ink:#e2e8f0; --dim:#94a3b8;
          --accent:#8b5cf6; --line:#334155; }}
  @media (prefers-color-scheme: light) {{
    :root {{ --bg:#f8fafc; --card:#ffffff; --ink:#0f172a; --dim:#64748b; --line:#e2e8f0; }}
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; padding:2rem 1rem; font:16px/1.5 system-ui, sans-serif; background:var(--bg); color:var(--ink); }}
  main {{ max-width:820px; margin:0 auto; }}
  h1 {{ margin:0 0 .25rem; font-size:1.6rem; }}
  p.sub {{ margin:0 0 1.25rem; color:var(--dim); }}
  p.sub a {{ color:var(--accent); text-decoration:none; }}
  #q {{ width:100%; padding:.8rem 1rem; font-size:1.05rem; border:1px solid var(--line);
       border-radius:.6rem; background:var(--card); color:var(--ink); outline:none; }}
  #q:focus {{ border-color:var(--accent); }}
  #meta {{ margin:.75rem 0 1rem; color:var(--dim); font-size:.9rem; }}
  .folder {{ margin:1.25rem 0 .5rem; font-size:.85rem; letter-spacing:.06em; text-transform:uppercase; color:var(--dim); }}
  .hit {{ display:block; padding:.7rem .9rem; margin:.4rem 0; background:var(--card); border:1px solid var(--line);
          border-radius:.6rem; text-decoration:none; color:inherit; }}
  .hit:hover {{ border-color:var(--accent); }}
  .hit .t {{ font-weight:600; }}
  .hit .w {{ color:var(--dim); font-size:.92rem; }}
  .hit .tags {{ color:var(--accent); font-size:.8rem; margin-inline-start:.5rem; }}
  .lang {{ float:right; color:var(--dim); font-size:.75rem; border:1px solid var(--line);
           border-radius:.4rem; padding:.05rem .4rem; }}
  html[dir=rtl] .hit .w {{ direction:rtl; text-align:right; display:block; }}
</style>
</head>
<body>
<main>
  <h1>🗄️ Prompt Stash</h1>
  <p class="sub">{total} copy-paste prompts · plain .txt ·
     <a href="https://github.com/Ziadtareks/prompt-stash">back to the repo</a></p>
  <input id="q" type="search" placeholder="Search by task, title, tag… (try: meeting, عقد, excel, phishing)"
         autocomplete="off" autofocus>
  <div id="meta"></div>
  <div id="results"></div>
  <noscript>This search page needs JavaScript; the full library lives in the
    <a href="https://github.com/Ziadtareks/prompt-stash/tree/main/prompts">prompts/ folder</a>.</noscript>
</main>
<script id="search-data" type="application/json">{data}</script>
<script>
  const INDEX = JSON.parse(document.getElementById('search-data').textContent);
  const q = document.getElementById('q'), meta = document.getElementById('meta'),
        out = document.getElementById('results');
  const folderName = f => (f.charAt(0).toUpperCase() + f.slice(1)).replace('-', ' ');
  function render() {{
    const needle = q.value.trim().toLowerCase();
    const words = needle.split(/\\s+/).filter(Boolean);
    const hits = INDEX.prompts.filter(p => {{
      const hay = (p.title + ' ' + p.when_to_use + ' ' + p.folder + ' ' + p.tags.join(' ')).toLowerCase();
      return words.every(w => hay.includes(w));
    }});
    meta.textContent = words.length ? hits.length + ' of ' + INDEX.total + ' prompts match'
                                    : 'All ' + INDEX.total + ' prompts — type to filter';
    out.innerHTML = '';
    let folder = null;
    for (const p of hits) {{
      if (p.folder !== folder) {{
        folder = p.folder;
        const h = document.createElement('div'); h.className = 'folder';
        h.textContent = folderName(folder); out.appendChild(h);
      }}
      const a = document.createElement('a');
      a.className = 'hit';
      a.href = 'https://github.com/Ziadtareks/prompt-stash/blob/main/' + p.path;
      const lang = document.createElement('span'); lang.className = 'lang';
      lang.textContent = p.language.prompt + '→' + p.language.output;
      const t = document.createElement('div'); t.className = 't';
      t.textContent = p.title;
      const tags = document.createElement('span'); tags.className = 'tags';
      tags.textContent = p.tags.join(' · '); t.appendChild(tags);
      const w = document.createElement('div'); w.className = 'w';
      w.textContent = p.when_to_use; w.dir = 'auto';
      a.append(lang, t, w); out.appendChild(a);
    }}
  }}
  q.addEventListener('input', render); render();
</script>
</body>
</html>
"""


def render_search_html(index_json: str) -> str:
    index = json.loads(index_json)
    data = json.dumps(index, ensure_ascii=False, separators=(",", ":"))
    return SEARCH_TEMPLATE.format(total=index["total"], data=data)


def generate() -> dict[str, str]:
    """Return every generated file as {repo-relative path: content}."""
    records = load_records()
    index_json = render_index(records)
    out = {"prompts.json": index_json}
    for folder in FOLDER_META:
        out[f"prompts/{folder}/README.md"] = render_folder_readme(folder, records)
    out["docs/search.html"] = render_search_html(index_json)
    return out


def main() -> None:
    for rel, content in generate().items():
        (ROOT / rel).write_text(content, encoding="utf-8", newline="\n")
    records = load_records()
    folders = {name: sum(1 for r in records if r["folder"] == name) for name in FOLDER_META}
    print(f"prompts.json, folder READMEs and docs/search.html written: "
          f"{len(records)} prompts across {len(folders)} folders")
    for name in FOLDER_META:
        print(f"  {name}: {folders[name]}")


if __name__ == "__main__":
    main()
