#!/usr/bin/env python3
"""Build prompts.json and the per-folder READMEs from the prompt files.

Standard library only. Idempotent: run after any prompt change so the docs
and the machine-readable index never drift from the actual files.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / "prompts"
LANG_RE = re.compile(r"^Language: prompt=(EN|AR) \| output=(EN|AR|EN\+AR|user-choice)$")

FOLDER_META = {
    "debugging": ("🐞", "Fix the thing that broke — websites, Windows, printers, batteries, email."),
    "work": ("💼", "Meetings, emails, priorities and the career conversations in between."),
    "content": ("✍️", "Posts, captions, hooks and calendars — bilingual where it matters."),
    "study": ("📚", "Understand faster and remember longer — notes, quizzes, plans."),
    "business": ("🏪", "Run a small business: clients, quotes, invoices, complaints."),
    "dev": ("💻", "Everyday developer repairs — git, SQL, logs, reviews, Docker."),
    "daily": ("🌱", "Money, food, sleep, habits and the choices in between."),
    "ai-coding": ("🤖", "Work with AI coding tools: better prompts, tests, refactors, reviews."),
    "career": ("🎯", "Job search and promotion — CVs, interviews, LinkedIn, negotiations."),
    "marketing": ("📣", "Ads, WhatsApp, landing pages and seasons for small businesses."),
    "files-data": ("🗃️", "Tame spreadsheets, PDFs and folders into clean answers."),
    "security-basics": ("🔐", "Defensive everyday security — no fear, just checklists."),
    "arabic-life": ("🇪🇬", "Formal Arabic, Egyptian dialect and Egypt paperwork — done right."),
}


def parse(f: Path) -> dict:
    lines = f.read_text(encoding="utf-8").splitlines()
    lang = LANG_RE.match(lines[2])
    tags = [t.strip() for t in lines[3][len("Tags: "):].split(",") if t.strip()]
    idx = next(i for i, l in enumerate(lines) if l.strip() == "# Variables")
    variables = [re.match(r"^- \{([a-z0-9_]+)\}:", l).group(1)
                 for l in lines[idx + 1:] if l.startswith("- {")]
    return {
        "title": lines[0].strip(),
        "when_to_use": lines[1][len("When to use it:"):].strip(),
        "folder": f.parent.name,
        "path": f.relative_to(ROOT).as_posix(),
        "language": {"prompt": lang.group(1), "output": lang.group(2)},
        "tags": tags,
        "variables": variables,
    }


records = [parse(f) for f in sorted(PROMPTS.glob("*/*.txt"))]
records.sort(key=lambda r: (r["folder"], r["path"]))

folders = {name: sum(1 for r in records if r["folder"] == name) for name in FOLDER_META}
index = {
    "name": "Prompt Stash",
    "total": len(records),
    "folders": folders,
    "prompts": records,
}
(ROOT / "prompts.json").write_text(
    json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

for folder, (emoji, blurb) in FOLDER_META.items():
    items = [r for r in records if r["folder"] == folder]
    out = [f"# {emoji} {folder} — {len(items)} prompts", "",
           f"> {blurb}", "",
           "<!-- GENERATED by scripts/build_index.py — edit the .txt files, not this table. -->", "",
           f"← Back to the [main README](../../README.md).", "",
           "| File | Title | When to use it | Language |",
           "|---|---|---|---|"]
    for r in items:
        name = Path(r["path"]).name
        lang = f"{r['language']['prompt']}→{r['language']['output']}"
        out.append(f"| [`{name}`]({name}) | {r['title']} | {r['when_to_use']} | {lang} |")
    out += ["", "## File format", "",
            "Title · when-to-use · `Language:` · `Tags:` · body · `# Variables` · `# Example values`.",
            "See the [main README](../../README.md#-file-format) for details.", ""]
    (PROMPTS / folder / "README.md").write_text("\n".join(out), encoding="utf-8")

print(f"prompts.json written: {len(records)} prompts across {len(folders)} folders")
for name in FOLDER_META:
    print(f"  {name}: {folders[name]}")
