# Task 4: real one-line docs for every variable that had a lazy explanation.
# Keys are variable names (they are unique across the library).

VAR_DOCS = {
 "academic_level": "required, level of study, e.g. \"high school senior\" or \"2nd-year university\"",
 "access_risk": "required, what the lost device can reach, e.g. \"bank app, Gmail, work Slack\"",
 "account_about": "required, what your account posts about, e.g. \"home bakery in Cairo\"",
 "account_details": "required, your reference numbers with the provider, e.g. \"account 0123456789\"",
 "account_list": "optional, platforms you have accounts on, e.g. \"Instagram, TikTok, an old forum\"",
 "accounts": "required, the accounts to protect, e.g. \"Gmail, bank app, Instagram\"",
 "action": "required, the single action you want recipients to take, e.g. \"reply to pre-order\"",
 "action_needed": "required, whether the reader must act, e.g. \"no action needed\" or \"approve by Friday\"",
 "activities": "required, what you'll do on the network, e.g. \"email, client calls\"",
 "affected_service": "required, the breached or affected account, e.g. \"old forum account\"",
 "ai_output": "required, summary or paste of what the AI produced",
 "alert_type": "required, how you learned of the problem, e.g. \"notification email\"",
 "angle": "required, your non-obvious strength or situation, e.g. \"no degree, promoted from within\"",
 "announcement_type": "required, occasion type, e.g. \"shop opening\" or \"condolence notice\"",
 "app_summary": "required, what the app does, who uses it, main actions",
 "application_stats": "required, your funnel numbers, e.g. \"40 applications, 1 interview\"",
 "assumed_purpose": "required, what you think the code does, e.g. \"debounced search box\"",
 "at_risk": "required, what you think you lost, e.g. \"uncommitted changes on feature-x\"",
 "attachments": "optional, files you're attaching, e.g. \"passport copy, payment receipt\"",
 "attempts": "required, resolution attempts so far with ticket numbers, e.g. \"4 calls, ticket 8812\"",
 "attendees": "required, who attends and their roles, e.g. \"ops manager, 2 warehouse leads\"",
 "audience_and_channel": "required, who the announcement reaches and where, e.g. \"family WhatsApp groups\"",
 "audience_and_funnel": "required, audience and warmth, e.g. \"parents 28-45, cold traffic\"",
 "audience_and_goal": "required, audience and the action you want, e.g. \"job seekers, goal = follows\"",
 "audience_and_problem": "required, who it's for and the problem it kills",
 "audience_and_promise": "required, audience and the transformation you offer",
 "audience_language": "required, language your audience/recruiters use, e.g. \"English recruiters in Gulf\"",
 "audience_scope": "required, who the offer targets, e.g. \"new customers only\"",
 "availability": "required, when you can start, e.g. \"immediately\" or \"one month notice\"",
 "available_data": "required, data you have each period, e.g. \"enrollments, revenue, attendance\"",
 "available_hours": "required, realistic hours available, e.g. \"6 today\" or \"10 per week\"",
 "avoiding": "required, the task you keep postponing, e.g. \"the tax filing\"",
 "backup_status": "required, current backup state, e.g. \"nothing backed up\"",
 "battery_health": "optional, battery stats if visible, e.g. \"78% max capacity\"",
 "bedtime_now": "required, when you actually sleep now, e.g. \"1:30 AM\"",
 "bottom_line": "required, your escalation limit, e.g. \"pause their ongoing work\"",
 "bounce_error": "optional, the exact bounce text, e.g. \"550 mailbox unavailable\"",
 "budget": "required, budget with currency, e.g. \"15,000 EGP\"",
 "business_and_angle": "required, business + seasonal angle, e.g. \"grooming kits, gifting\"",
 "business_and_aov": "required, business + average order value, e.g. \"tutoring center, 800 EGP/month\"",
 "business_and_news": "required, business + what you're announcing, e.g. \"Sweet Meter, winter menu\"",
 "business_and_platform": "required, business + the review platform that matters, e.g. \"workshop, Google Maps\"",
 "business_type": "required, business category, e.g. \"dental clinic\"",
 "buyer_and_desire": "required, who buys and why they want it, e.g. \"students, carry laptop + notes\"",
 "cancellation_policy": "required, your reschedule/cancel rules, e.g. \"free up to 24h before\"",
 "changes_summary_or_diff": "required, summary or paste of the changes",
 "channel": "required, where the message arrived, e.g. \"SMS\" or \"Instagram DM\"",
 "channels": "required, where word of mouth happens today, e.g. \"parent WhatsApp groups\"",
 "child_details": "required, child's full name, class and school, e.g. \"Youssef Ahmed, 5/B, Al-Nour School\"",
 "city_and_rent": "required, city + rent for context, e.g. \"Giza, 9,500 EGP/month\"",
 "claimed_sender": "required, who the message claims to be from, e.g. \"a courier company\"",
 "client_and_request": "required, client + what they asked for, e.g. \"Cafe Rivea, logo + menu\"",
 "client_type": "required, relationship to the debtor, e.g. \"client for 2 years\"",
 "codebase_patterns": "required, conventions the AI must match, e.g. \"server actions + optimistic UI\"",
 "comments": "required, the actual comments, one per line",
 "company_appeal": "required, what appeals to you about the company, e.g. \"customer-first fintech\"",
 "compared": "optional, what you already compared, e.g. \"fresh clone, .env exists\"",
 "competency": "required, the behavior being tested, e.g. \"ownership\"",
 "competitor_price": "optional, competitor price range if known, e.g. \"8,000-30,000 EGP\"",
 "competitors": "required, competitor names, links, or descriptions",
 "connected_accounts": "required, accounts that reset via the affected one, e.g. \"Gmail resets bank + social\"",
 "connection": "required, how the printer connects, e.g. \"USB\", \"Wi-Fi\"",
 "constraints": "required, hard limits, e.g. \"solo dev, 3 months, ~30 USD/mo hosting\"",
 "content_topics": "required, what you post about, e.g. \"portraits, Cairo streets\"",
 "content_type": "required, what the message contains, e.g. \"PDF attachment + links\"",
 "contents": "required, what's inside the issue, e.g. \"3 sections: pricing math, scripts, tool\"",
 "context": "required, situation context, e.g. \"Cairo, polite but firm Arabic\"",
 "contract_type": "required, contract type + your side, e.g. \"freelance contract, I'm the freelancer\"",
 "cover_person": "required, who covers you + contact, e.g. \"Omar, omar@company.com\"",
 "current_behavior": "required, the code's public behavior that must not change",
 "current_field": "required, your current field + years, e.g. \"accountant, 4 years\"",
 "current_habit": "required, how you download software today, e.g. \"first download button in search\"",
 "current_locations": "required, where the data lives today, e.g. \"one laptop + phone\"",
 "current_routine": "required, your typical day, e.g. \"wake 7, work 9-5, dinner 8\"",
 "current_state": "required, your honest password situation, e.g. \"same password everywhere\"",
 "current_to_target": "required, current title → wanted title, e.g. \"accountant → senior accountant\"",
 "current_vs_target": "required, role you have vs role you want, e.g. \"accountant → FP&A analyst\"",
 "customer_message": "required, the customer's message, redacted, pasted as-is",
 "customer_name": "required, customer name, e.g. \"Khaled\"",
 "customers": "required, who your customers are, e.g. \"parents in school WhatsApp groups\"",
 "cv_file": "required, CV file name, e.g. \"Ahmed-Hassan-Accountant-CV.pdf\"",
 "data": "required, the data to visualize — paste it or describe it",
 "data_about": "required, what the data covers + period, e.g. \"sales by branch, Jan-Jun\"",
 "data_size": "required, rough size, e.g. \"~180 GB\"",
 "data_source": "required, where the data came from, e.g. \"WhatsApp orders pasted in\"",
 "date_time": "required, exact booking date and time, e.g. \"Tuesday March 4, 5:30 PM\"",
 "dates": "required, exact dates, e.g. \"leave June 10-24, back June 25\"",
 "dates_and_reason": "required, dates + reason, e.g. \"12-14 May, illness with certificate\"",
 "days": "required, trip length in days, e.g. \"4\"",
 "days_available": "required, study days from today, e.g. \"10\"",
 "days_per_week": "required, training days per week, e.g. \"3\"",
 "deadline": "required, date or timeframe, e.g. \"Friday 5pm\" or \"in 3 weeks\"",
 "deadlines": "optional, known deadlines mapped to tasks, e.g. \"taxes in 5 days\"",
 "definition_of_done": "required, done criteria, e.g. \"works logged-in only, undo toast, empty state\"",
 "deploy_method": "required, how you deploy, e.g. \"GitHub integration, auto-deploy\"",
 "desired_resolution": "required, outcome you want, e.g. \"fix in 72h or penalty-free cancellation\"",
 "device": "required, device + age, e.g. \"iPhone 11, battery 3 years old\"",
 "device_and_lock": "required, device + lock state, e.g. \"Android, was unlocked in my hand\"",
 "devices": "required, your devices, e.g. \"Windows 11 laptop + Android phone\"",
 "dialect": "required, dialect/register, e.g. \"Egyptian\" or \"formal-leaning Egyptian\"",
 "differentiator": "required, why it's not the cheap version, e.g. \"hand-printed, wash-proof\"",
 "document_type": "required, the PDF type, e.g. \"bank statement, Jan-Mar\"",
 "due_days": "required, payment deadline in days, e.g. \"14\"",
 "duration": "required, how long it has been like this, e.g. \"3 months\"",
 "edge": "required, your claimed differentiator, e.g. \"healthier sugar options\"",
 "edge_cases": "optional, known data quirks, e.g. \"blank amounts, names with extra spaces\"",
 "email_setup": "required, your email setup, e.g. \"own domain via hosting\"",
 "emergency_line": "optional, how you can be reached for true emergencies, e.g. \"phone for contract clients\"",
 "environment": "required, usage environment, e.g. \"on bed, dusty room\"",
 "error_output": "optional, the build/run error text",
 "essay_question": "required, the essay question or title",
 "evidence": "required, promotion evidence with numbers, e.g. \"ran month-end close solo for 6 months\"",
 "exam_date": "required, exam date, e.g. \"June 20\"",
 "exam_focus": "optional, topic to prioritize, e.g. \"cell division\"",
 "exam_style": "required, question format, e.g. \"MCQ\" or \"mixed\"",
 "excuse": "optional, the debtor's excuse, e.g. \"silent\" or \"processing\"",
 "expected_behavior": "required, what should happen, e.g. \"order created + redirect to confirmation\"",
 "expected_objection": "required, the pushback you expect, e.g. \"headcount freeze\"",
 "experience": "required, relevant experience + proof, e.g. \"3 years, 12 delivered stores\"",
 "exposure": "required, what's publicly visible about you, e.g. \"workplace, kids' photos, district\"",
 "failure_type": "required, how email fails, e.g. \"bounce\" or \"spam folder\"",
 "feature_idea": "required, the feature in your own words, e.g. \"users save posts to read later\"",
 "field_and_level": "required, your field + years, e.g. \"finance graduate, 2 years reporting\"",
 "fields_needed": "required, columns to extract, e.g. \"date, description, debit, credit\"",
 "file_types": "required, what piles up, e.g. \"invoices, contracts, course files, photos\"",
 "fitness_level": "required, honest level, e.g. \"never trained\"",
 "fixed_costs": "required, monthly fixed costs list, e.g. \"rent 5,500, utilities 1,200\"",
 "flavor": "required, SQL dialect, e.g. \"Postgres\" or \"MySQL\"",
 "focus_topics": "required, topics to prioritize, e.g. \"periodic trends, ionic bonding\"",
 "formal_text": "required, the fus'ha text to convert",
 "formality": "required, dialect formality level, e.g. \"polished but friendly\"",
 "format": "required, output format, e.g. \"one-page email\" or \"slide\"",
 "formula": "required, the formula to explain, e.g. \"F = m·a\"",
 "framework": "required, test framework, e.g. \"Vitest\" or \"pytest\"",
 "frequency": "required, how often in this situation, e.g. \"3 cafés a week\"",
 "friction": "required, your objection to the fix, e.g. \"what if I forget the master password\"",
 "from_to": "required, migration from → to with versions, e.g. \"class components → hooks\"",
 "git_output": "required, current git status/log/error output",
 "gut_feeling": "optional, what already feels off, e.g. \"it says unlimited revisions somewhere\"",
 "happy_moment": "required, peak satisfaction moment, e.g. \"delivery at home\"",
 "hours_per_day": "required, honest study hours per day, e.g. \"2\"",
 "hours_per_week": "required, realistic hours per week, e.g. \"8\"",
 "idea": "required, the business idea, e.g. \"weekend dessert stall via Instagram pre-orders\"",
 "idea_constraints": "optional, offer types you'd consider, e.g. \"free delivery over % off\"",
 "important_accounts": "required, your critical accounts, e.g. \"bank, Gmail, work email, Instagram\"",
 "incident": "required, what happened + how long ago, e.g. \"phone snatched 40 minutes ago\"",
 "invoice_details": "required, number, amount, due date, days overdue, e.g. \"INV-014, 12,500 EGP, 23 days late\"",
 "issue_topic": "required, this issue's topic",
 "item_and_price": "required, item + asking vs market price, e.g. \"iPhone 13, 14k vs ~24k EGP\"",
 "items_and_prices": "required, line items + prices, e.g. \"logo 6,000 EGP, menu 3,500 EGP\"",
 "items_list": "required, what was delivered or worked on",
 "job_focus": "required, the 3 requirements that matter most",
 "job_requirements": "required, the posting's requirements, pasted",
 "key_details": "required, names, date, time, place exactly as they should appear",
 "key_dimensions": "required, what a file name must show, e.g. \"client, date, deliverable, version\"",
 "key_facts": "required, facts to include, e.g. \"student ID 20210435, semester starts Sep 14\"",
 "key_question": "required, the question the reader cares about, e.g. \"which branch to expand\"",
 "key_sources": "optional, sources or points that must appear",
 "language_and_tone": "required, language + tone, e.g. \"Egyptian Arabic, friendly\"",
 "last_worked": "required, when it last worked + what changed, e.g. \"last week; router replaced\"",
 "last_year": "optional, last season's result, e.g. \"sold out in 4 days\"",
 "law_context": "optional, rent-law context if known, e.g. \"new-rent contract\"",
 "length_and_dialect": "required, length/time limit + dialect, e.g. \"90 seconds, Egyptian\"",
 "leverage": "required, your negotiating leverage, e.g. \"competing offer, achievements\"",
 "link_purpose": "optional, what your bio link promotes, e.g. \"booking form\"",
 "list_purpose": "required, what the lists are + why reconcile, e.g. \"payments vs customers\"",
 "location": "required, city/market or place, e.g. \"Nasr City, Cairo\"",
 "location_carrier": "required, country + carrier, e.g. \"Egypt, Vodafone\"",
 "location_or_link": "required, address or meeting link",
 "locations": "required, where you live/travel, e.g. \"Egypt, frequent Saudi visits\"",
 "losing_where": "required, where you lose to competitors, e.g. \"they look more trustworthy online\"",
 "machine": "required, machine + age + use, e.g. \"Dell G3, 4 years, gaming\"",
 "main_worry": "optional, your biggest concern, e.g. \"security of user input\"",
 "margin": "required, margin headroom, e.g. \"40%\"",
 "market": "required, market/currency context, e.g. \"EGP, Cairo fintech market\"",
 "match_key": "required, what makes records the same, e.g. \"phone number, fallback name\"",
 "matching_proof": "required, your best requirement matches with proof",
 "material": "required, stories or qualities to mention, 2-3 max",
 "medium": "required, where the chart appears, e.g. \"investor slide\"",
 "meeting_cadence": "required, frequency + duration, e.g. \"biweekly, 30 min\"",
 "memory_list": "required, rough memories/achievements to draw from",
 "mess_description": "required, the chaos you can see, e.g. \"dates as text, lost leading zeros\"",
 "mess_factors": "optional, known mess factors, e.g. \"Arabic/English spellings, extra spaces\"",
 "message": "required, the suspicious message with links replaced by [LINK]",
 "method_and_endpoint": "required, e.g. \"POST /v1/orders\"",
 "minutes_per_session": "required, minutes per session, e.g. \"30\"",
 "mistake_list": "required, your mistakes: question idea, your answer, correct answer",
 "monthly_income": "required, take-home income, e.g. \"14,000 EGP\"",
 "must_haves": "required, non-negotiables, e.g. \"auth, payments, file uploads, email\"",
 "must_keep": "required, what must not be lost, e.g. \"family photos, work chats\"",
 "my_background": "required, your background in ~3 lines",
 "my_business": "required, your business + contact info, e.g. \"Nour Designs, hello@…\"",
 "my_details": "required, your name and role, e.g. \"Sara, sales support\"",
 "my_error": "required, the exact error on your machine",
 "my_goal": "required, what you want from the meeting/reply, e.g. \"feedback on promotion readiness\"",
 "my_priority": "required, what you care about most, e.g. \"payment and revisions\"",
 "my_prompt": "required, the prompt that produced bad output",
 "my_setup": "required, your setup, e.g. \"Windows 11, Python 3.13, pip\"",
 "my_side": "required, which side you are, e.g. \"the tenant\"",
 "my_skills": "required, your skills + honest levels, e.g. \"Excel advanced, no SQL\"",
 "need": "required, what you need the library to do, e.g. \"form validation with schema reuse\"",
 "note_type": "required, note type, e.g. \"absence excuse, 3 days\"",
 "number_of_cards": "required, card count, e.g. \"15\"",
 "number_of_hashtags": "required, hashtag count, e.g. \"20\"",
 "numbers": "required, the figures you have, e.g. \"2.8s p95\" or \"18,000 now, asking 24,000\"",
 "objective": "required, ad objective, e.g. \"messages\" or \"purchases\"",
 "occasion": "required, the occasion, e.g. \"graduation with honors\"",
 "occasion_and_dates": "required, occasion + dates, e.g. \"Eid al-Adha, ~June 6\"",
 "occasion_and_relation": "required, occasion + your relationship, e.g. \"best friend's engagement\"",
 "offer": "required, the offer, e.g. \"online course, 1,200 EGP/month\"",
 "offer_and_deadline": "required, offer + real deadline, e.g. \"10% for first 30, closes Thursday\"",
 "offer_and_price": "required, what you sell + price",
 "open_to": "required, what you're open to, e.g. \"full-time\" or \"freelance + full-time\"",
 "options": "required, the realistic options, 2-4",
 "pain": "required, what hurts about the code, e.g. \"can't unit test the charging logic\"",
 "pain_points": "required, current naming pains, e.g. \"final_final chaos\"",
 "parent_contact": "required, your name/phone as sign-off, e.g. \"his mother, 0100xxxxxxx\"",
 "paste_cv": "required, full CV text between the markers",
 "paste_dockerfile": "required, Dockerfile or compose file between the markers",
 "paste_list_a": "required, first list, one record per line",
 "paste_list_b": "optional, second list to reconcile against",
 "paste_message_links_redacted": "required, message pasted with every link replaced by [LINK]",
 "pattern": "required, failure pattern, e.g. \"drops every 20-30 min, worse at night\"",
 "payment_demand": "required, how they want payment, e.g. \"500 EGP wallet transfer to reserve\"",
 "payment_terms": "required, deposit % and deadlines, e.g. \"50% deposit\"",
 "pc_type": "required, PC age/type/RAM, e.g. \"5-year-old laptop, 8GB RAM, HDD\"",
 "personal_details": "optional, names + detail to weave in, e.g. \"engineering faculty, first in class\"",
 "phone_type": "required, phone model + storage, e.g. \"Samsung A52, 128GB\"",
 "pickup_person": "optional, who picks up + relation + ID note",
 "planned_change": "required, what you intend to change, e.g. \"fire search only after 3+ chars\"",
 "platform_and_frequency": "required, platform + honest frequency, e.g. \"IG + TikTok, 4/week\"",
 "platform_and_length": "required, platform + length, e.g. \"Instagram Reels, 45s\"",
 "platform_and_slides": "required, platform + slide limit, e.g. \"LinkedIn, 8 slides\"",
 "position_and_property": "required, your side + property type, e.g. \"tenant, 2-bedroom apartment\"",
 "position_and_source": "required, position + where you found it, e.g. \"accountant, referral\"",
 "preparedness": "required, current protections, e.g. \"Find My on, last backup 3 days ago\"",
 "pressure_lines": "required, urgency lines used, e.g. \"3 people asking, first to pay gets it\"",
 "price": "required, your price, e.g. \"18,000 EGP\"",
 "price_and_channel": "required, price + where it's sold, e.g. \"350 EGP, Instagram + own site\"",
 "price_point": "required, starting price, e.g. \"from 8,000 EGP\"",
 "printer_type": "required, brand + type + age, e.g. \"Canon inkjet, 3 years\"",
 "priorities": "required, decision criteria in your words, e.g. \"money, family, growth\"",
 "problem": "required, what's wrong, e.g. \"image 1.4GB, rebuilds everything each change\"",
 "problem_and_dates": "required, what failed + since when, e.g. \"outage 12 days, 3 tickets since June 1\"",
 "process": "required, how promotion decisions work, e.g. \"annual cycle, manager recommends\"",
 "product_and_margin": "required, product + price + margin, e.g. \"custom cakes, 700 EGP, 45% margin\"",
 "product_and_price": "required, product/service + price",
 "product_and_qty": "required, product specs + quantity, e.g. \"500 kraft bags, 25x30cm, printed\"",
 "product_and_specs": "required, product + honest specs, e.g. \"cotton tote, 38x42cm, 12 colors\"",
 "promotion": "optional, anything to promote this month, e.g. \"Eid pre-orders\"",
 "proof": "required, usable proof, e.g. \"340 students, 4.8 rating\"",
 "provider_and_service": "required, provider + service, e.g. \"WE home internet\"",
 "purpose": "required, purpose, e.g. \"choose the Q3 courier\" or \"decide or align\"",
 "question_count": "required, number of questions, e.g. \"12\"",
 "raw_update": "required, your raw technical update",
 "reader": "required, who will read the rewrite, e.g. \"client owner\"",
 "reader_cares": "required, what that reader cares about, e.g. \"app speed and their bill\"",
 "readers": "required, who reads the report and what they decide",
 "real_context": "required, context the AI should have had, e.g. \"Next.js 15, Supabase auth, Tailwind\"",
 "reason": "required, why now, e.g. \"slow season + clear the June schedule\"",
 "recent_changes": "required, recent changes, e.g. \"Windows update last week\"",
 "recent_updates": "required, wins/blockers/worries since the last 1:1",
 "recipient_type": "required, recipient type, e.g. \"university admissions office\"",
 "recipients": "required, who receives the message, e.g. \"past buyers on broadcast list\"",
 "refund_amount": "required, amount + destination, e.g. \"1,200 EGP to the original card\"",
 "rejection_context": "required, role + how far you got, e.g. \"final round, lost to internal hire\"",
 "relationship": "required, relationship to recipient, e.g. \"admitted student\"",
 "reminders_sent": "required, reminders so far, e.g. \"1 friendly email\"",
 "reply_language": "required, language to reply in, e.g. \"Arabic\"",
 "report_type": "required, report type + frequency, e.g. \"monthly tutoring-center report\"",
 "request_you_sent": "required, the request you sent, secrets redacted",
 "requested_action": "required, what the message wants, e.g. \"pay a fee via a link\"",
 "requirements": "required, the target requirements list, pasted",
 "resolution": "required, what you can offer, e.g. \"resend express + 10% coupon\"",
 "response_body": "required, the API response body, secrets redacted",
 "review_status": "required, current count + rating, e.g. \"7 reviews, 4.9\"",
 "riskiest": "required, the riskiest part, e.g. \"the payment form component\"",
 "role_and_company": "required, role + company type, e.g. \"data analyst at a Cairo fintech\"",
 "role_and_field": "required, role + field, e.g. \"ops coordinator at an e-commerce startup\"",
 "rough_content": "required, your rough points or data for the deck",
 "router_lights": "required, router light behavior on drop, e.g. \"internet light turns orange\"",
 "run_context": "required, how tests run, e.g. \"CI, pure functions, no DB\"",
 "runway_months": "required, months of instability you can afford, e.g. \"0 (need salary)\"",
 "savings_goal": "required, goal + amount, e.g. \"20,000 EGP emergency fund\"",
 "scale": "required, honest expected scale, e.g. \"500 users/day\"",
 "schedule": "required, send gaps, e.g. \"day 0 / 2 / 5\"",
 "schema": "required, tables + columns, pasted",
 "scope": "required, migration scope, e.g. \"12 components in one module\"",
 "scores": "required, score vs full mark, e.g. \"62/100\"",
 "search_habits": "required, how you look for files, e.g. \"by client name and rough date\"",
 "seller_signals": "required, profile signals, e.g. \"account 2 weeks old, duplicated listings\"",
 "service": "required, the service you sell or priced, e.g. \"brand identity package\"",
 "services": "optional, companion services needed, e.g. \"Postgres via compose\"",
 "setup": "required, router/ISP setup, e.g. \"TP-Link router, WE home internet\"",
 "sheet_layout": "required, columns/headers + sample rows, e.g. \"A: date, B: salesperson\"",
 "shipping_constraint": "required, big-bang vs continuous, e.g. \"must ship continuously\"",
 "signals": "optional, rapport/signals from the process, e.g. \"they liked my test\"",
 "signup_context": "required, what they signed up for, e.g. \"downloaded lunchbox ideas PDF\"",
 "situation": "required, the negotiation situation, e.g. \"annual review next week\"",
 "situation_and_ask": "required, situation + what you need to say or ask",
 "skills_and_evidence": "required, top skills + evidence, e.g. \"Power BI (built 6 dashboards)\"",
 "software_and_os": "required, software needed + OS, e.g. \"video editor, Windows 11\"",
 "space_eaters": "optional, known space hogs, e.g. \"WhatsApp 30GB, gallery 40GB\"",
 "stack_hosting": "required, stack + hosting, e.g. \"Django + Postgres on a small VPS\"",
 "stage_format": "required, interview stage + format + duration, e.g. \"technical panel, 45 min\"",
 "stop_code": "required, the stop code/error text, e.g. \"CRITICAL_PROCESS_DIED\"",
 "storage": "required, where files live, e.g. \"Google Drive shared\"",
 "store_name": "required, store/business name, e.g. \"Nour Home\"",
 "stuck_point": "required, the exact step where you're stuck, e.g. \"the factoring step\"",
 "study_method": "required, how you studied, e.g. \"reread the textbook twice, no practice\"",
 "subject_and_exam": "required, subject + exam type, e.g. \"physics final\"",
 "subject_and_level": "required, subject + level, e.g. \"grade 10 algebra\"",
 "subscriber_pain": "required, the subscriber's main problem, e.g. \"no time to plan meals\"",
 "subscribers": "required, who subscribes and why",
 "supplier_language": "required, supplier's language, e.g. \"Arabic\"",
 "supplier_type": "required, supplier kind, e.g. \"local distributor\"",
 "suspects": "optional, your suspicions, e.g. \"database, server size\"",
 "symptoms": "required, symptoms, e.g. \"loud fan, hot keyboard, sudden shutdowns\"",
 "table_sizes": "required, rough row counts, e.g. \"orders ~200k rows\"",
 "target": "required, what the effort targets, e.g. \"the June 22 launch decision\"",
 "target_audience": "required, who you want to attract, e.g. \"brands and couples\"",
 "target_client": "required, your ideal client, e.g. \"Egyptian/Gulf retail shops\"",
 "target_field": "required, the field/role you're moving to, e.g. \"data analyst\"",
 "target_shape": "required, the clean output shape, e.g. \"one row per order\"",
 "task_list": "required, your tasks, one per line, messy is fine",
 "team_and_files": "required, team + file types, e.g. \"3-person studio: briefs, invoices\"",
 "team_context": "required, solo or shared, e.g. \"team of 3 pushes to main daily\"",
 "temptation": "required, why unofficial sources tempt you, e.g. \"price\"",
 "term": "required, the English term, e.g. \"opportunity cost\"",
 "terms_list": "required, the terms on your papers, e.g. \"توكيل، إخلاء طرف، قسيمة\"",
 "threat_model": "required, who you're worried about, e.g. \"scammers + future employers\"",
 "time_and_slides": "required, time limit + slide count, e.g. \"10 min, 8 slides\"",
 "time_budget": "required, time available, e.g. \"45 minutes Thursday evening\"",
 "time_commitment": "required, hours you can invest, e.g. \"nights + weekends\"",
 "time_since_deploy": "required, time since the deploy, e.g. \"25 minutes\"",
 "time_window": "required, roughly when in the log, e.g. \"around 14:03\"",
 "timeline": "required, delivery timeline, e.g. \"3-4 weeks\"",
 "tone_and_language": "required, tone + language, e.g. \"practical, English\"",
 "tool": "required, tool + version, e.g. \"Excel 365\" or \"Google Sheets\"",
 "tools_available": "required, what you have, e.g. \"no VPN, unlimited mobile data\"",
 "topic_and_goal": "required, topic + what the deck must achieve, e.g. \"persuade funding\"",
 "topic_and_point": "required, topic + its core point",
 "topic_and_takeaway": "required, topic + the one takeaway",
 "topics": "required, topics to cover, e.g. \"3 courier quotes, packaging idea\"",
 "topics_list": "required, topics + difficulty, e.g. \"kinematics easy, momentum hard\"",
 "toucher": "required, who asks for the review, e.g. \"me on delivery\"",
 "traffic": "required, traffic source + temperature, e.g. \"warm Instagram followers\"",
 "transaction": "required, the transaction you're doing, e.g. \"buying a small apartment\"",
 "transferables": "optional, skills that might transfer, e.g. \"Excel advanced, monthly reporting\"",
 "tricky_ones": "optional, comments needing care, e.g. \"the overpriced comment\"",
 "trip_type": "required, trip type, e.g. \"beach + light hiking\"",
 "unique_angle": "required, what makes you different, e.g. \"same-day preview gallery\"",
 "usage": "required, usage pattern, e.g. \"maps + hotspot daily\"",
 "vague_report": "required, the vague bug report, e.g. \"checkout sometimes doesn't work\"",
 "valid_days": "required, quote validity in days, e.g. \"14\"",
 "voice": "required, your voice, e.g. \"warm + a little cheeky\"",
 "voice_of_customer": "required, what customers actually say, e.g. review and DM quotes",
 "volume": "required, volumes/repeat potential, e.g. \"reorder monthly if quality holds\"",
 "wake_up_time": "required, required wake time, e.g. \"6:30 AM\"",
 "weather": "required, forecast/season, e.g. \"hot days, cool nights\"",
 "what_changed": "required, what the deploy changed, e.g. \"bumped a payment library major\"",
 "what_happened": "required, what you did / what git did",
 "what_i_do": "required, what you or your brand does, e.g. \"home bakery in Cairo\"",
 "what_i_was_doing": "required, what you were doing when it broke",
 "what_included": "required, exactly what the price includes",
 "what_is_wrong": "required, wrong results, slow, or the error text",
 "what_slow": "required, what exactly is slow, e.g. \"products API response\"",
 "what_to_protect": "required, what you must not lose, e.g. \"photos, client work, thesis\"",
 "what_went_wrong": "required, what failed for the customer, honest, e.g. \"wrong size shipped twice\"",
 "what_wrong": "required, what's wrong with the AI output, e.g. \"wrong stack, ignores constraints\"",
 "when_hot": "required, when it overheats, e.g. \"20 min into any game\"",
 "when_it_happens": "required, when it crashes, e.g. \"random, 2-3 times a day\"",
 "when_slow": "required, when it's slow, e.g. \"startup and Chrome\"",
 "when_started": "required, when it started + what changed, e.g. \"after yesterday's deploy\"",
 "where": "required, where it happens, e.g. \"web checkout, Chrome mostly\"",
 "who_affected": "required, who's affected, e.g. \"all Wi-Fi devices, wired is fine\"",
 "who_buys": "required, who actually buys today, e.g. \"working moms 30-45\"",
 "who_else": "optional, who else needs to find files, e.g. \"my accountant once a year\"",
 "who_i_am": "required, who you are, e.g. \"freelance photographer\"",
 "word_count": "required, target word count, e.g. \"1000\"",
 "working_setup": "required, the working machine's versions, e.g. \"Python 3.11 + poetry.lock\"",
 "works_where": "required, where it works, e.g. \"teammate's Mac and CI both green\"",
 "worries": "optional, what you're most worried about, e.g. \"explaining gaps\"",
 "worry": "required, your main objection/worry, e.g. \"losing my phone while traveling\"",
 "yes_no_and_when": "required, did it work before + when, e.g. \"worked fine yesterday\"",
 "your_business": "required, your business/name + contact details",
}
