# Task 1/2/3/5 per-file content data.
# of: OUTPUT FORMAT body section; cl: replacement clarifying line (None = keep standard);
# ar: arabic style block key (None = EN only); add: extra RULES lines; body: full rewrite.

STD = "- If critical information is missing, ask up to 3 clarifying questions first; otherwise proceed with clearly-stated assumptions."

def D(of, cl=None, ar=None, add=None, body=None):
    return {"of": of, "cl": cl, "ar": ar, "add": add or [], "body": body}

COMPLETE = "Input-complete prompt: if the pasted material is unreadable or clearly incomplete, say exactly what is missing instead of proceeding on assumptions."

F = {
 # ── debugging ──
 "debugging/website-error-fix": D("Six numbered sections as headings, in order. ≤450 words total; ≤3 causes; each check ≤3 steps; fix ≤6 steps. Lead with WHAT HAPPENED."),
 "debugging/bsod-explain": D("Six numbered sections in order. ≤350 words; causes ranked 1-3; each section ≤5 lines. Lead with IN PLAIN WORDS.", cl="If the stop code is unrecognized or ambiguous, say so and give the top 2 interpretations instead of guessing one."),
 "debugging/deploy-rollback": D("Six numbered sections in order, copy-paste commands where possible. ≤400 words; TRIAGE ≤2 lines. Lead with the TRIAGE call."),
 "debugging/slow-pc-fix": D("Five numbered sections in order. ≤350 words; ≤3 causes, ≤5 checks, fixes as numbered steps. Lead with TOP 3 CAUSES."),
 "debugging/wifi-drop-fix": D("Five numbered sections in order. ≤350 words; the 3-point test as a numbered list. Lead with LOCATE THE FAULT."),
 "debugging/printer-fix": D("Five numbered sections in order. ≤350 words; fix steps numbered, ≤8 steps. Lead with SYMPTOM TRIAGE."),
 "debugging/phone-storage-fix": D("Five numbered sections in order; cleanups as a table (Step | Frees | Risk). ≤350 words. Lead with FIND THE EATERS."),
 "debugging/battery-drain-fix": D("Five numbered sections in order. ≤350 words; settings fixes as exactly 5 bullets. Lead with HEALTH VS SETTINGS."),
 "debugging/overheating-fix": D("Five numbered sections in order. ≤350 words; free fixes ≤4 steps. Lead with NORMAL VS NOT.", cl="If the model or symptoms are ambiguous, ask up to 3 questions (age, when it overheats, shutdowns?) before the verdict."),
 "debugging/email-bounce-fix": D("Five numbered sections in order. ≤400 words; decode the real bounce codes quoted from my message. Lead with READ THE BOUNCE."),
 # ── work ──
 "work/meeting-notes-fix": D("Five numbered sections in order: TL;DR, KEY DECISIONS, ACTION ITEMS table, OPEN QUESTIONS, FOLLOW-UP EMAIL. ≤250 words of summary; action table ≤10 rows. Lead with the TL;DR.", cl=COMPLETE),
 "work/reply-tone": D("Four numbered sections: VERSION A, VERSION B, WHAT CHANGED (≤3 bullets), RED FLAG CHECK (≤1 line). Version A ≤120 words, Version B ≤80 words. Lead with VERSION A.", cl=COMPLETE),
 "work/cv-bullets": D("Four numbered sections in order: exactly {number_of_bullets} bullets, keyword list (5), weak spots (2), summary line (2 lines). Each bullet ≤15 words. Lead with THE BULLETS.", cl=COMPLETE),
 "work/one-on-one-prep": D("Five numbered sections in order; agenda ≤5 bullets; each section ≤4 lines. Lead with THE 5-POINT AGENDA."),
 "work/salary-negotiation-email": D("Five numbered sections in order; the email ≤150 words; fallback ≤2 lines. Lead with THE ANCHOR."),
 "work/out-of-office-writer": D("Four numbered sections: MESSAGE (≤80 words), SHORT VERSION (2 sentences), URGENT ROUTING (1 sentence), CHECKLIST (4 items). Lead with THE MESSAGE.", cl=COMPLETE),
 "work/presentation-outline": D("Five numbered sections in order; slide table sized to the stated limit; opening hook written out verbatim. Lead with THE STORY SPINE."),
 "work/meeting-agenda": D("Five numbered sections in order; agenda table (Item | Time | Leader | Outcome) summing to the stated duration minus 5 minutes. Lead with THE VERDICT.", cl="If the topic list clearly cannot fit the stated duration, say what to cut or move to email — ask at most 1 question."),
 "work/jargon-simplifier": D("Five numbered sections in order; rewrite ≤5 bullets of ≤20 words; one-liner ≤25 words. Lead with THE ONE-LINER.", cl=COMPLETE),
 "work/task-priority-sort": D("Five numbered sections in order: sort table (one row per task), TODAY'S 3 (exactly 3), time check, 15-minute first step, delete list. Lead with THE SORT."),
 # ── content ──
 "content/captions-ar": D("Four numbered sections in order: 5 captions (labeled 1-5 with their style), emoji note merged into each caption, CTA inside each, dialect bonus (2). Each caption ≤200 characters. Lead with CAPTIONS.", ar="eg"),
 "content/hashtags": D("Five numbered sections in order; the set split BROAD/NICHE/COMMUNITY with counts summing to the requested number; dead-tag check replaces, never just warns. Lead with THE SET."),
 "content/bio-maker": D("Four numbered sections: 5 bios with character counts stated, trim notes, keyword check, ONE-LINER. Each bio ≤ the platform limit. Lead with BIOS."),
 "content/video-script-short": D("Five numbered sections: 3 hooks, timed script table (Seconds | Line | Visual), retention beat, one-sentence CTA, caption + 5 hashtags. Lead with THE HOOK."),
 "content/post-hooks": D("Four numbered sections: exactly 10 hooks (2 each of curiosity/stat/story/contrarian/pain), top-3 ranking with reasons, first paragraph for #1, anti-cliché check. Lead with TEN HOOKS.", cl=COMPLETE),
 "content/content-calendar": D("Five numbered sections in order; calendar table with one row per post for the stated frequency × 4 weeks; every post idea writable in 20 minutes. Lead with THE MIX."),
 "content/carousel-outline": D("Five numbered sections; slide table sized exactly to the stated limit (Headline ≤8 words, Body ≤25 words); 3 cover alternatives. Lead with THE ARC."),
 "content/product-description": D("Five numbered sections: title line (≤8 words), short description (≤30 words), full description (100-150 words), practical block, second language version. Lead with TITLE LINE.", ar="both"),
 "content/newsletter-intro": D("Four numbered sections: 5 subject lines (≤45 chars), preview text (40-90 chars), intro (3-5 lines), bridge sentence. Lead with SUBJECT LINE OPTIONS.", cl=COMPLETE),
 "content/comment-reply": D("Four numbered sections: one reply per comment in order (≤2 sentences each), complaint handling, troll decision, pin suggestion. Lead with REPLIES.", cl=COMPLETE),
 # ── study ──
 "study/summarize-lesson": D("Five numbered sections in order: TL;DR (≤3 sentences), key points, definitions table, 3 exam questions with 2-line answers, confusion check. ≤400 words. Lead with the TL;DR.", cl=COMPLETE),
 "study/flashcards-maker": D("Three numbered sections: the card table (exactly the requested count; # | Question | Answer), type-mix note with percentages, exactly 3 ⚠️ flags. Lead with THE CARDS.", cl=COMPLETE),
 "study/exam-revision": D("Five numbered sections: day-by-day table (Day | Topics | Hours | Goal), daily shape (1 line), mock slot, last-day list, drop list (ranked). Hours per day never exceed the stated cap. Lead with THE PLAN."),
 "study/translate-term": D("Five numbered sections in order: translation + transliteration, plain-English explanation (≤2 sentences), شرح عربي (جملتان), example pair, don't-confuse-with (1-2 terms). Lead with TRANSLATION.", cl=COMPLETE),
 "study/essay-outline": D("Four numbered sections: 2 thesis options, the outline (section-by-section with a word split summing to the stated count), one topic sentence per body paragraph, research list (3-5 source types). Lead with THESIS OPTIONS.", cl=COMPLETE),
 "study/practice-quiz": D("Four numbered sections: quiz (exactly the requested count, easy→hard), MCQ options where applicable, separate ANSWER KEY with 1-line explanations, 3 flagged traps. Lead with THE QUIZ.", cl=COMPLETE),
 "study/feynman-explain": D("Interactive session: one message per exchange — (a) what I got right (1 line), (b) numbered gaps, (c) exactly one Socratic question per gap. Final polish only after I pass: 5-line version + 3 exam questions.", cl="Interaction rules: one question per message, wait for my answer, never explain a gap directly before I attempt it, minimum 2 rounds.", add=["Never dump the full explanation up front — the polish step is earned."]),
 "study/formula-explainer": D("Six numbered sections in order: in-words sentence, symbol table, intuition (2-3 lines), worked example line by line with units balancing, when-to-use + lookalike, memory hook (1 line). Lead with IN WORDS.", cl=COMPLETE),
 "study/homework-hint": D("Structured tutoring exchange: restate the question (1 line) → Hint Level 1 only → wait for my attempt → one level per message → full solution only after I answer or give up → close with one similar practice question.", cl="Interaction rules: one hint level per message, never the final answer before my attempt, if I pasted no attempt ask what I tried first."),
 "study/mistake-log-analyzer": D("Five numbered sections: pattern classification with percentages, dominant problem (1 blunt line), a specific fix per pattern, study-method verdict (1 line), 3 next-exam actions. Lead with THE PATTERN.", cl=COMPLETE),
 # ── business ──
 "business/store-reply": D("Five numbered sections: the read (1 line), Version A, Version B, de-escalation sentence (if angry), DO-NOT-SAY (1 line). Versions ≤100 words each, in the requested language. Lead with WHAT THEY REALLY WANT.", cl=COMPLETE),
 "business/invoice-words": D("Five numbered sections: header block, items table, totals block, terms block (≤4 lines), overdue reminder (≤3 sentences). Plain-text layout, copy-paste ready. Lead with THE INVOICE.", cl=COMPLETE),
 "business/price-calc-explain": D("Five numbered sections: value map (one line per inclusion), 3 reframes, 3 ready replies (≤4 sentences each), honest verdict (1 line), discount rule. Lead with VALUE MAP."),
 "business/booking-confirm": D("Four numbered sections: SMS (≤300 characters), email (subject + ≤120 words), reminder line (1), no-show line (1). Lead with SMS VERSION.", cl=COMPLETE),
 "business/refund-apology": D("Four numbered sections: 3 subject lines, the message (≤150 words: own it → refund details → timeline → gesture → invite back), timeline honesty (1 line), 3 banned phrases. Lead with SUBJECT LINE OPTIONS.", cl=COMPLETE),
 "business/quotation-writer": D("Five numbered sections: header, items table with a scope note per line, totals, terms (validity, deposit, timeline, exclusions), acceptance line. Plain-text, copy-paste ready. Lead with QUOTATION HEADER.", cl=COMPLETE),
 "business/contract-summary": D("Six numbered sections: the deal (≤5 lines), clause table (Clause | Plain meaning | Green/Yellow/Red), red flags quoted briefly, what's missing, negotiation questions (3), disclaimer line. Lead with THE DEAL.", cl=COMPLETE),
 "business/supplier-email": D("Five numbered sections: the email (subject + ≤120 words), leverage line (1), negotiation reply, sample request (≤3 lines), local WhatsApp version. Lead with THE EMAIL."),
 "business/late-payment-chaser": D("Five numbered sections: stage verdict (1 line), next-stage email (≤120 words), final notice (≤150 words), 5-line phone script, prevention (2 changes). Lead with WHERE WE ARE."),
 "business/idea-check": D("Five numbered sections: verdict (1 line: promising / promising with changes / risky / avoid), demand test (3 questions), unit math with [FILL] marks, 3 killers, cheapest first step with a go/no-go number. Lead with THE VERDICT."),
 # ── dev ──
 "dev/readme-writer": D("Four numbered sections: pitch (1 line), complete README in one markdown block, quick-start gaps flagged, screenshot TODO (1 line). Lead with THE PITCH.", cl=COMPLETE),
 "dev/commit-message": D("Five numbered sections: best message in a code block (subject ≤50 chars + body ≤3 lines), 2 alternatives, type verdict (1 line), split advice, breaking-change footer if needed. Lead with BEST MESSAGE.", cl=COMPLETE),
 "dev/regex-explain": D("Six numbered sections: plain-English sentence, token table (every symbol), match demo on my sample, 2 edge cases, fragility verdict, 4+4 test cases. Lead with PLAIN ENGLISH.", cl=COMPLETE),
 "dev/sql-fix": D("Six numbered sections: diagnosis (1 line), bug in plain words (≤3 sentences), fixed SQL with per-change comments, why it works (≤3 sentences), index suggestion or 'skip', verify steps. Lead with DIAGNOSIS.", cl="If the goal is ambiguous (e.g. which rows are 'wrong'), ask exactly one question; otherwise proceed with stated assumptions."),
 "dev/api-error": D("Five numbered sections: plain-words meaning (general + specific), 3 ranked causes tied to my request, fixes with a corrected request, 1-minute retest command, retry rule (1 line). Lead with IN PLAIN WORDS.", cl=COMPLETE),
 "dev/git-rescue": D("Five numbered sections: safety-net command first, diagnosis paragraph, rescue commands each with a plain-English line and expected output, verification checks, force-push warning if relevant. Lead with SAFETY NET.", cl="If the state is ambiguous from my output, ask me to run one read-only command (git log --oneline --graph) and reply before any fix."),
 "dev/log-analyzer": D("Five numbered sections: root-error line quoted with timestamp, the 2-4 preceding lines, plain-words failure, noise filter, next step. Lead with THE ROOT ERROR.", cl=COMPLETE),
 "dev/code-reviewer": D("Five numbered sections: verdict (1 line), findings table (P0/P1/P2), explicit security pass, fix diff for the worst section only, one genuine compliment. Lead with VERDICT.", cl=COMPLETE),
 "dev/env-setup-debug": D("Five numbered sections: ranked suspect list, version-check commands, the fix step by step, clean-room fallback, prevention (1 file). One change at a time. Lead with SUSPECT LIST.", cl=COMPLETE),
 "dev/dockerfile-fix": D("Five numbered sections: the breaking line quoted, corrected Dockerfile with comments, size/speed pass applied only where relevant, run checks, build+run verify commands. Lead with THE BREAKER.", cl=COMPLETE),
 # ── daily ──
 "daily/habit-plan": D("Six numbered sections: 2-minute version, one anchor sentence, Weeks 1-4 table, one tracking method, never-miss-twice rule, obstacle counter-move. Week-1 total <5 minutes. Lead with THE 2-MINUTE VERSION."),
 "daily/budget-split": D("Five numbered sections: warning check (1 line, only if fixed costs >60%), split table (Category | Amount | %), one weekly allowance number, 3 cuts ranked with savings, emergency-fund line. Lead with WARNING CHECK or THE SPLIT."),
 "daily/trip-pack-list": D("Six sections as checkbox lists: documents, clothes with quantities, tech, health/small, bag split, leave-at-home (5). No prose paragraphs. Lead with DOCUMENTS & MONEY.", cl=COMPLETE),
 "daily/workout-plan": D("Six numbered sections: weekly schedule, session tables (Exercise | Sets | Reps | Rest), warm-up/cooldown, one form cue per exercise, one progression rule, safety line. Total fits the stated minutes. Lead with WEEKLY SCHEDULE."),
 "daily/sleep-routine": D("Six numbered sections: target bedtime math, 60-minute wind-down in 15-minute blocks, 2-3 disruptor counter-moves, bedroom checklist (4), can't-sleep protocol, 14-day tracker table. Lead with TARGET BEDTIME."),
 "daily/weekly-meal-planner": D("Five numbered sections: week table (Day | Meal | Ingredients | Prep time), grouped shopping list with estimated total vs budget, budget check (1 line), 2 batch-prep shortcuts, flex night. Lead with THE WEEK."),
 "daily/expenses-review": D("Six numbered sections: category table (Category | Total | %), needs-vs-wants split, 3 leaks with monthly totals, suspect verdict (1 line), 3 fixes with savings, one good thing (1 line). Lead with THE PICTURE.", cl=COMPLETE),
 "daily/difficult-conversation-rehearsal": D("Interactive rehearsal: SETUP READ (1 line) → stay in character 2-3 exchanges → COACHING (worked/weak moment/rewrite) → stress-test round → CHEAT SHEET (opening, 3 objection responses, closing line, exit line). One exchange per message.", cl="Interaction rules: one exchange per message, wait for my replies, never break character before the coaching step."),
 "daily/decision-matrix": D("Five numbered sections: 5-7 criteria with weights (sum 100), scored matrix table, weighted totals + gap verdict, gut-check (1 kind sentence), 3 tie-breaker questions with the cheapest way to answer them. Lead with THE CRITERIA."),
 "daily/weekly-reset": D("Five numbered sections: timed agenda filling the stated budget, capture checklist from my roles/slips, one reflection question, Monday first hour, stick plan + 10-minute fallback. Lead with THE AGENDA."),
 # ── ai-coding ──
 "ai-coding/feature-to-prompt": D("Five numbered sections: refined feature (states + permissions listed), one copy-paste build-prompt block, exactly 5 acceptance statements, scope-guard line, 2 pre-written follow-ups. Lead with THE REFINED FEATURE."),
 "ai-coding/code-explainer": D("Five numbered sections: big picture (2-3 sentences), numbered walkthrough in execution order, key concepts (2 lines each), landmines, change plan tied to my stated intent. Lead with THE BIG PICTURE.", cl=COMPLETE),
 "ai-coding/refactor-request": D("Five numbered sections: 3 smells with locations, ordered refactor plan (one verifiable step each), refactored code, behavior-lock proof (characterization test), deliberately-skipped list. Lead with SMELLS.", cl=COMPLETE),
 "ai-coding/test-writer": D("Five numbered sections: test plan (behaviors list), complete runnable test file, 3 missed edge cases with tests, mock decisions with reasons, run commands. Lead with TEST PLAN.", cl=COMPLETE),
 "ai-coding/bug-repro-steps": D("Five numbered sections: ≤3 clarifying questions (only if needed), 3 hypotheses with trigger hints, numbered repro recipe with expected-vs-actual at the divergence, minimization notes, ticket-ready title + body. Lead with QUESTIONS or HYPOTHESES.", cl=COMPLETE),
 "ai-coding/library-picker": D("Five numbered sections: the 2-4 real contenders (including stdlib/no-library), comparison table, one committed verdict + flip condition, install + minimal usage + gotcha, exit plan (wrap-behind-module). Lead with THE FIELD."),
 "ai-coding/migrate-code": D("Five numbered sections: inventory (change vs stay), stages where each ends shippable with a proof check, strangler plan if continuous, risky-stage tests + rollback, cleanup checklist. Lead with INVENTORY."),
 "ai-coding/performance-fix": D("Five numbered sections: baseline measurement (exact tool + number to record), verdict per suspect, ranked likely bottlenecks with detection signals, highest-impact fix (+second), before/after proof table. Lead with MEASURE FIRST."),
 "ai-coding/prompt-improver": D("Five numbered sections: diagnosis ranked, rewritten prompt in one copy-paste block, why-it-works (1 line per change), reusable context block, iteration follow-up prompt. Lead with THE DIAGNOSIS.", cl=COMPLETE),
 "ai-coding/architecture-suggest": D("Five numbered sections: component diagram in text, one-line boring-tech justification per box, core data model, 3 painful-to-change decisions to make now, postponed list with triggers. Lead with THE ARCHITECTURE."),
 # ── career ──
 "career/cv-reviewer": D("Five numbered sections: 6-second test, keyword gaps, findings table (Section | Problem | Fix), 3 bullet rewrites with [FILL] marks, verdict (send / fix-and-send / rebuild). Lead with THE 6-SECOND TEST.", cl=COMPLETE),
 "career/cover-letter-writer": D("Five numbered sections: hook (1 line), match paragraphs, angle sentence, close, the full letter assembled within the stated length. Lead with THE HOOK.", cl=COMPLETE),
 "career/linkedin-profile-fix": D("Five numbered sections: recruiter search keywords, 3 headline options (≤220 chars), About section (5-8 lines), experience rewrite rules + one worked example, quick wins. Lead with THE KEYWORDS."),
 "career/interview-prep": D(  # full rewrite below (was the weak scorer)
  "Interactive session: confirm setup in 1 line, then one question per message. After each answer: score /10, what worked, the missing piece, a model-answer skeleton (not a script). Round 2 re-asks my 2 weakest questions reworded. Close with STAR stories to prepare, worry defusals, and 3 questions to ask them."),
 "career/star-story-builder": D("Five numbered sections: story selection (+runner-up), STAR story ≤250 words with [FILL] for the missing number, flex kits for 3 nearby questions, delivery notes (90-second box + ending). Lead with STORY SELECTION.", cl=COMPLETE),
 "career/career-switch-plan": D("Five numbered sections: honest gap (3-5 skills ranked by difficulty), transfer map restated in target language, month-by-month table ending in applications, 2 portfolio artifacts, financial guardrail + go/no-go signal. Lead with THE HONEST GAP."),
 "career/freelance-profile": D("Five numbered sections: 3 search-first titles, overview (first 2 lines survive the preview cut), 3 packages with delivery days, proof section plan, trust blocks (FAQ + response time). Lead with TITLE.", cl=COMPLETE),
 "career/promotion-case": D("Five numbered sections: thesis (1 sentence), evidence table (3-5 rows, strongest first), one-page memo, objection pre-emption, conversation script ending in a dated review. Lead with THE THESIS.", cl=COMPLETE),
 "career/rejection-reply": D("Four numbered sections: the reply (4-6 sentences, ≤120 words), specific feedback ask, stay-in-touch line, 3 replies to never send. Lead with THE REPLY.", cl=COMPLETE),
 "career/skills-gap-map": D("Five numbered sections: gap table (Requirement | My level | Severity), translation of what I already have, closing order sized to stated hours, proof artifact per gap, honest framing for unclosable gaps before the deadline. Lead with THE GAP TABLE.", cl=COMPLETE),
 # ── marketing ──
 "marketing/ad-copy-writer": D("Five numbered sections: 2 angles (1 line each), 5 ad variations (primary ≤90 words + headline ≤40 chars + CTA), search ads if Google, 2-ad test plan with decision metric, compliance pass. Lead with THE ANGLE."),
 "marketing/email-sequence": D("Five numbered sections: the arc (1 line per email), email 1, email 2, email 3, settings note. Each email ≤140 words, one CTA each, no pitch before email 3. Lead with THE ARC."),
 "marketing/discount-offer": D("Five numbered sections: mechanic + why it beats %-off, margin math with max discount, framing rules (honest urgency), announcement + reminder posts (≤60 words each), guardrails. Lead with THE MECHANIC."),
 "marketing/customer-persona": D("Five numbered sections: named persona, job-to-be-done in customer words, triggers + 3 objections with counter-messages, ranked channels, one-line message using their vocabulary. Lead with THE PERSONA.", cl=COMPLETE),
 "marketing/competitor-teardown": D("Five numbered sections: per-competitor pitch (1 line each), their engine, gap matrix (factor | them | me), the opening (1 sentence), 3 affordable 30-day moves. Lead with THEIR PITCH."),
 "marketing/landing-copy": D("Five numbered sections: promise stack (3 headlines + subheadline), section map with 1-2 lines of copy each, FAQ (5 objections, 2 lines each), CTA options + microcopy, conversion notes. Lead with THE PROMISE STACK."),
 "marketing/whatsapp-broadcast": D("Five numbered sections: message (≤80 words), status version (≤40 words), follow-up (1 message), segmentation exclusions, anti-block do/don't list. Lead with THE MESSAGE."),
 "marketing/review-request": D("Five numbered sections: the trigger moment (1 line), 3 ask scripts, friction killer (direct link + staff card), unhappy-customer divert script, daily habit + target. Lead with THE MOMENT."),
 "marketing/referral-offer": D("Five numbered sections: reward structure with amounts the stated margin survives, the trigger moment + exact ask line, zero-app mechanics, one-time announcement text, 3 abuse guards. Lead with THE REWARD STRUCTURE."),
 "marketing/seasonal-campaign": D("Five numbered sections: campaign concept (1 line), 3-phase dated timeline (tease/peak/last-call), the offer, capacity + delivery cutoff, budget split with stop/double metric. Lead with THE ANGLE."),
 # ── files-data ──
 "files-data/excel-formula": D("Five numbered sections: paste-ready formula referencing my columns, piece-by-piece explanation, edge-case behavior, alternative approach, 3 test rows with expected results. Lead with THE FORMULA.", cl=COMPLETE),
 "files-data/csv-cleaner": D("Five numbered sections: preserve-first setup, diagnosis ranked, ordered cleaning steps with exact clicks, traps (phone zeros, date flips), 4 final sanity checks. Lead with PRESERVE FIRST.", cl=COMPLETE),
 "files-data/data-summarizer": D("Six numbered sections: headline answer to my question (1 sentence + number), summary table of aggregates, 3 standouts, supported comparisons, caveats, one chart spec (type + axes). Lead with THE HEADLINE.", cl=COMPLETE),
 "files-data/file-organizer": D("Five numbered sections: folder tree, naming pattern with 5 real + 4 wrong examples, phased migration (nothing deleted in round one), 2 keeping-alive habits, search upgrade. Lead with THE STRUCTURE."),
 "files-data/pdf-extract": D("Five numbered sections: the extracted table, formatting notes (numbers bare, one date format, Arabic preserved), extraction warnings per row, control totals vs the document, re-extraction tips. Lead with THE TABLE.", cl=COMPLETE),
 "files-data/sql-from-question": D("Five numbered sections: readable SQL for my dialect, clause-by-clause walkthrough, assumptions list, performance note for my table sizes, one variation teaching the delta. Lead with THE QUERY.", cl=COMPLETE),
 "files-data/chart-picker": D("Five numbered sections: chart type + why it beats alternatives, exact spec (axes, sort, format, highlight), headline written as the finding, honesty check, 5-minute build steps. Lead with THE CHART."),
 "files-data/duplicate-finder": D("Five numbered sections: within-list duplicates grouped, cross-list matches (probable ones labeled), only-in-A/only-in-B gap, normalization rules as steps, cleanup actions (keep rule per cluster). Lead with DUPLICATES WITHIN.", cl=COMPLETE),
 "files-data/report-skeleton": D("Five numbered sections: reading-order structure, metrics table (5-7 rows: Metric | This period | Last | Change | Target), narrative sentence patterns, red-flag section format, the assembled template. Lead with THE STRUCTURE."),
 "files-data/naming-convention": D("Five numbered sections: the pattern (segments defined), 8 correct + 4 wrong examples, sort guarantee + fixes, version marker system, rollout (pinned summary + amnesty plan). Lead with THE PATTERN."),
 # ── security-basics ──
 "security-basics/password-checkup": D("Five numbered sections: core idea (3 lines), 2-3 manager options compared + today's pick, migration order (email first), passphrase method with a fictional worked example, recovery plan. Lead with THE CORE IDEA.", cl="Never request real passwords. If my description implies a specific credential, replace it with a placeholder and move on."),
 "security-basics/phishing-spotter": D("Five numbered sections: verdict + 2 strongest signals, red-flag list (1 line each), official-channel verification path, if-already-clicked/paid triage, scam-family lesson. Lead with THE VERDICT.", cl=COMPLETE),
 "security-basics/2fa-setup-guide": D("Five numbered sections: method ladder with trade-offs, safety-net setup BEFORE enabling, per-account plan with steps, my-worry answer, yearly 10-minute checkup. Lead with METHOD LADDER."),
 "security-basics/scam-check": D("Five numbered sections: risk score + 2 deciding signals, classic pattern match, free verification checklist, safe-transaction protocol, if-already-paid steps. Lead with RISK SCORE."),
 "security-basics/breach-response": D("Five numbered sections: contain (first 30 min), stop-the-dominoes order, lock-the-doors checklist, damage assessment (skipped checks), 6-month fallout watch. Lead with CONTAIN."),
 "security-basics/public-wifi-safety": D("Five numbered sections: real risks ranked vs movie version, HTTPS shield explanation, tool plan from what I have, 5-minute pre-connect checklist, the nevers + safe alternatives. Lead with REAL RISKS."),
 "security-basics/device-loss-plan": D("Five numbered sections: minutes 0-10 lock/locate, 10-30 cut the money (SIM, banks, reset email), 30-60 remote sign-out + work IT, evidence for police/insurance, recovery + prevention. Lead with MINUTE 0-10."),
 "security-basics/backup-plan": D("Five numbered sections: 3-2-1 mapped to my devices/budget, exact folder list to protect, automation setup per device, offline/versioned copy for ransomware, 15-minute restore drill + reminder. Lead with 3-2-1 TRANSLATED."),
 "security-basics/privacy-audit": D("Five numbered sections: self-search method, exposure triage (keep/restrict/remove + why), forgotten-account hunt, 3 highest-impact settings per platform, ongoing habits. Ordered by impact per minute of effort. Lead with THE SELF-SEARCH."),
 "security-basics/safe-downloads": D("Five numbered sections: official source + impostor-site pattern, fake-download-button recognition, 30-second verification checks, cracked-software reality + legit alternatives, phone-specific rules. Lead with THE OFFICIAL SOURCE."),
 # ── arabic-life ──
 "arabic-life/formal-arabic-email": D("خمسة أقسام بالترتيب: سطر الموضوع، النص الكامل، الطلب مصاغًا بجملة واحدة، ملاحظات الصقل (2-3)، قالب التذكير. لا تتجاوز 200 كلمة في النص. ابدأ بسطر الموضوع.", ar="msa", cl=COMPLETE),
 "arabic-life/complaint-letter-eg": D("خمسة أقسام: الشكوى بالعربية، النسخة الإنجليزية، مسار التصعيد، حزمة الأدلة، نسخة المنشور العام (≤50 كلمة). ابدأ بالشكوى العربية.", ar="msa", cl=COMPLETE),
 "arabic-life/occasion-messages": D("Four numbered sections: for each length (short/medium/long) give 2-3 labeled variants at different formality levels (فصحى رسمية → مصرية ودية), the personal-touch version, the 20-second spoken version, DON'TS (2). Lead with the VARIANTS.", ar="occ", cl=COMPLETE),
 "arabic-life/rental-contract-explain": D("خمسة أقسام: الصفقة في 5 أسطر، جدول البنود (البند | المعنى ببساطة | الأخضر/الأصفر/الأحمر)، البنود الحمراء مقتبسة، البنود العادلة الناقصة، قائمة تفاوض بصيغة (البند الحالي ← المقترح). ابدأ بالصفقة.", ar="msa", cl=COMPLETE),
 "arabic-life/arabic-speech-notes": D("خمسة أقسام: الهيكل، النص كاملًا بعلامات الوقف (…)، شدة القصة (ما يُحذف)، ملاحظات الإلقاء (3)، نسخة الـ30 ثانية عند التلعثم. الالتزام الصارم بمدد الزمن. ابدأ بالهيكل.", ar="eg", cl=COMPLETE),
 "arabic-life/school-note-writer": D("Four numbered sections: the formal Arabic note, the 3-line WhatsApp version, the medical-certificate line if illness-related, polite-firmness phrasing if needed. Lead with THE NOTE.", ar="msa", cl=COMPLETE),
 "arabic-life/dialect-coach": D("Five numbered sections: the conversion, change-log table (الفصحى | المصرية | ليه), register warnings, spoken-flow marks, regional check. Lead with THE CONVERSION.", cl=COMPLETE),
 "arabic-life/arabic-job-application": D("Five numbered sections: subject line, Arabic email (4-6 lines), English version, salary-question phrasing, attachment checklist. Lead with SUBJECT LINE.", ar="both", cl=COMPLETE),
 "arabic-life/legal-terms-explain": D("خمسة أقسام: جدول المصطلح بمصطلح، خريطة خطوات المعاملة، الفخ الشائع لكل مستند، 5 أسئلة للمحامي/المكتب، تنبيه التكاليف بعلامات [تأكد]. ابدأ بجدول المصطلحات.", ar="msa", cl=COMPLETE),
 "arabic-life/announcement-maker": D("Five numbered sections: the full Arabic announcement in the occasion's register, short WhatsApp version, print layout guidance, tone guardrails for this type, distribution timing note. Lead with THE ANNOUNCEMENT.", ar="occ", cl=COMPLETE),
}

AR_BLOCKS = {
 "msa": ["ARABIC STYLE",
   "- Write the Arabic in Modern Standard Arabic (فصحى رسمية معاصرة) — formal/official register; Egyptian dialect would undermine the purpose. State nothing else about variety: MSA is fixed here.",
   "- Use the conventional opening and closing for this document type (e.g. «تحية طيبة وبعد،» … «وتفضلوا بقبول فائق الاحترام والتقدير») and the correct honorifics for the recipient's rank.",
   "- Never invent law numbers, article citations, official fees, or form names — write [تحقق] where one would go.",
   "- Native phrasing only: no calques from English, no stiff translated word order, no padded formality. Short, precise sentences."],
 "eg": ["ARABIC STYLE",
   "- Write the Arabic in natural Egyptian dialect (مصري) exactly as a native would say it out loud — casual, warm, current.",
   "- No calques from English, no fus'ha padding, no over-formal connectors; short spoken sentences with normal Egyptian connectors (يعني، بص، خلاص).",
   "- Keep proper nouns, numbers, and technical terms unchanged."],
 "both": ["ARABIC STYLE (for the Arabic half of the output)",
   "- Rewrite the meaning natively — never translate the English word by word.",
   "- Use Modern Standard Arabic for the formal deliverable and Egyptian dialect where the brief is casual; state which register each part uses.",
   "- Native rhythm and vocabulary: no stiff calques, no over-formal padding."],
 "occ": ["ARABIC STYLE",
   "- Offer every message in 2-3 labeled variants at different formality levels: formal fus'ha → polite standard → warm Egyptian.",
   "- Follow the occasion's cultural and religious conventions: the correct customary phrases for condolences, weddings, and Eid; never mix celebratory wording into solemn messages or vice versa; never use jokes or requests in condolence notes.",
   "- Egyptian dialect for warmth unless the recipient or channel demands fus'ha; no stiff calques from English."],
 "choice": ["If the requested output language is Arabic: use Egyptian dialect for casual/social content or Modern Standard Arabic for formal contexts — state which you used — and write natural native phrasing a native reader would actually say, never a stiff translation from English."],
}

# Second-pass coverage: Arabic-capable files whose entries above lack an ar key.
AR_ADD = {
 "study/translate-term": "msa",
 "marketing/landing-copy": "both",
 "arabic-life/dialect-coach": "eg",
 "business/store-reply": "choice",
 "career/cover-letter-writer": "choice",
 "career/freelance-profile": "choice",
 "career/linkedin-profile-fix": "choice",
 "content/comment-reply": "choice",
 "content/newsletter-intro": "choice",
 "content/post-hooks": "choice",
 "content/video-script-short": "choice",
 "daily/weekly-meal-planner": "choice",
 "marketing/ad-copy-writer": "choice",
 "marketing/email-sequence": "choice",
 "marketing/review-request": "choice",
 "marketing/whatsapp-broadcast": "choice",
 "study/flashcards-maker": "choice",
}
